production:
  clients:
    default:
      database: game-night
      hosts:
        - candidate.61.mongolayer.com:10658
        - candidate.57.mongolayer.com:10798
      options:
        user: davissp14
        password: ginger
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: game_night_development
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

test:
  clients:
    default:
      database: game_night_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
